import { Router } from 'express';
import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun, AlignmentType } from 'docx';
import { v4 as uuidv4 } from 'uuid';
import { documents, documentVersions, steps, auditLogs } from '../db/schema';
import { db } from '../db';
import { eq, desc } from 'drizzle-orm';
import { AuthRequest } from '../middleware/auth';
import * as fs from 'fs';
import * as path from 'path';

const router = Router();

// POST /api/docs/:id/export/pdf - Generate PDF export
router.post('/:id/export/pdf', async (req: AuthRequest, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id;

    // Get document with latest version
    const docRecords = await db.select().from(documents).where(eq(documents.id, id)).limit(1);
    
    if (docRecords.length === 0) {
      res.status(404).json({ error: 'Document not found' });
      return;
    }

    const doc = docRecords[0];

    // Get current version
    const versions = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, id))
      .orderBy(desc(documentVersions.versionNumber))
      .limit(1);

    const currentVersion = versions[0];

    // Get all steps for this version
    const docSteps = await db.select()
      .from(steps)
      .where(eq(steps.versionId, currentVersion.id))
      .orderBy(steps.order);

    // Log audit event
    await db.insert(auditLogs).values({
      id: uuidv4(),
      orgId: doc.orgId,
      userId: userId || null,
      action: 'document.export.pdf',
      entityType: 'document',
      entityId: id
    });

    // Create PDF document
    const pdfDoc = new PDFDocument({ 
      size: 'A4', 
      margins: { top: 50, bottom: 50, left: 50, right: 50 } 
    });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${doc.title.replace(/[^a-z0-9]/gi, '_')}.pdf"`);

    // Pipe PDF to response
    pdfDoc.pipe(res);

    // Cover Page
    pdfDoc.fontSize(24).text(doc.title, { align: 'center' });
    pdfDoc.moveDown(2);
    pdfDoc.fontSize(12).text(`Generated by Ronflow`, { align: 'center' });
    pdfDoc.text(`Version ${currentVersion.versionNumber}`, { align: 'center' });
    pdfDoc.text(`Date: ${new Date(doc.updatedAt).toLocaleDateString()}`, { align: 'center' });
    pdfDoc.text(`Author: ${doc.ownerId}`, { align: 'center' });
    pdfDoc.moveDown(3);
    pdfDoc.fontSize(10).text('Confidential - Internal Use Only', { align: 'center', color: '#999999' });
    
    pdfDoc.addPage();

    // Table of Contents
    pdfDoc.fontSize(18).text('Table of Contents', { underline: true });
    pdfDoc.moveDown(1);
    
    docSteps.forEach((step, index) => {
      pdfDoc.fontSize(11).text(`${index + 1}. ${step.title}`, { 
        link: `#step-${index + 1}`,
        underline: true,
        color: '#0066cc'
      });
    });

    pdfDoc.addPage();

    // Summary Section
    pdfDoc.fontSize(16).text('Procedure Summary', { underline: true });
    pdfDoc.moveDown(0.5);
    pdfDoc.fontSize(11).text(doc.summary || 'No summary provided.');
    pdfDoc.moveDown(1);

    // Prerequisites
    if (doc.prerequisites && doc.prerequisites.length > 0) {
      pdfDoc.fontSize(14).text('Prerequisites', { underline: true });
      pdfDoc.moveDown(0.5);
      doc.prerequisites.forEach((prereq: string) => {
        pdfDoc.fontSize(11).text(`• ${prereq}`);
      });
      pdfDoc.moveDown(1);
    }

    // Estimated Time
    pdfDoc.fontSize(11).text(`Estimated Completion Time: ${doc.estimatedTime || 'Not specified'}`);
    pdfDoc.moveDown(2);

    // Steps
    docSteps.forEach((step, index) => {
      const pageNum = pdfDoc.bufferedPageRange().start + 1;
      
      pdfDoc.fontSize(16).text(`Step ${index + 1}: ${step.title}`, { 
        underline: true,
        continued: false
      });
      pdfDoc.moveDown(0.5);
      
      pdfDoc.fontSize(11).text(step.description || 'No description available.');
      
      if (step.notes) {
        pdfDoc.moveDown(0.5);
        pdfDoc.fontSize(10).italic().text(`Note: ${step.notes}`, { color: '#666666' });
        pdfDoc.fontSize(11).unitalic();
      }

      // Placeholder for screenshot annotation
      pdfDoc.moveDown(1);
      pdfDoc.fontSize(10).text('[Screenshot would appear here in production]', { color: '#999999' });
      pdfDoc.moveDown(2);
    });

    // Footer on each page
    pdfDoc.on('pageAdded', () => {
      const pageCount = pdfDoc.bufferedPageRange().count;
      pdfDoc.fontSize(8).text(
        `Page ${pageCount} | Generated by Ronflow`,
        50,
        pdfDoc.page.height - 30,
        { align: 'right' }
      );
    });

    pdfDoc.end();

  } catch (error) {
    console.error('PDF export error:', error);
    res.status(500).json({ error: 'Failed to generate PDF export' });
  }
});

// POST /api/docs/:id/export/docx - Generate DOCX export
router.post('/:id/export/docx', async (req: AuthRequest, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id;

    // Get document
    const docRecords = await db.select().from(documents).where(eq(documents.id, id)).limit(1);
    
    if (docRecords.length === 0) {
      res.status(404).json({ error: 'Document not found' });
      return;
    }

    const doc = docRecords[0];

    // Get current version
    const versions = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, id))
      .orderBy(desc(documentVersions.versionNumber))
      .limit(1);

    const currentVersion = versions[0];

    // Get all steps
    const docSteps = await db.select()
      .from(steps)
      .where(eq(steps.versionId, currentVersion.id))
      .orderBy(steps.order);

    // Log audit event
    await db.insert(auditLogs).values({
      id: uuidv4(),
      orgId: doc.orgId,
      userId: userId || null,
      action: 'document.export.docx',
      entityType: 'document',
      entityId: id
    });

    // Build DOCX children array
    const children: any[] = [];

    // Title
    children.push(
      new Paragraph({
        text: doc.title,
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 }
      })
    );

    // Metadata
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by Ronflow | Version ${currentVersion.versionNumber} | ${new Date(doc.updatedAt).toLocaleDateString()}`,
            size: 20,
            color: '666666'
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 }
      })
    );

    // Summary
    children.push(
      new Paragraph({
        text: 'Procedure Summary',
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 }
      })
    );

    children.push(
      new Paragraph({
        children: [new TextRun({ text: doc.summary || 'No summary provided.', size: 22 })],
        spacing: { after: 300 }
      })
    );

    // Prerequisites
    if (doc.prerequisites && doc.prerequisites.length > 0) {
      children.push(
        new Paragraph({
          text: 'Prerequisites',
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 }
        })
      );

      doc.prerequisites.forEach((prereq: string) => {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: '• ', size: 22 }),
              new TextRun({ text: prereq, size: 22 })
            ],
            spacing: { after: 100 }
          })
        );
      });
    }

    // Estimated Time
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Estimated Completion Time: ${doc.estimatedTime || 'Not specified'}`,
            size: 22,
            bold: true
          })
        ],
        spacing: { before: 300, after: 400 }
      })
    );

    // Steps
    docSteps.forEach((step, index) => {
      children.push(
        new Paragraph({
          text: `Step ${index + 1}: ${step.title}`,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 400, after: 200 }
        })
      );

      children.push(
        new Paragraph({
          children: [new TextRun({ text: step.description || 'No description available.', size: 22 })],
          spacing: { after: 200 }
        })
      );

      if (step.notes) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `Note: ${step.notes}`,
                size: 20,
                italics: true,
                color: '666666'
              })
            ],
            spacing: { after: 300 }
          })
        );
      }
    });

    // Create DOCX document
    const docx = new Document({
      sections: [{
        properties: {},
        children
      }]
    });

    // Generate buffer
    const buffer = await Packer.toBuffer(docx);

    // Set response headers
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${doc.title.replace(/[^a-z0-9]/gi, '_')}.docx"`);

    // Send buffer
    res.send(buffer);

  } catch (error) {
    console.error('DOCX export error:', error);
    res.status(500).json({ error: 'Failed to generate DOCX export' });
  }
});

// GET /api/docs/:id/versions - List all versions
router.get('/:id/versions', async (req: AuthRequest, res) => {
  try {
    const { id } = req.params;

    const versions = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, id))
      .orderBy(desc(documentVersions.versionNumber));

    res.json(versions);
  } catch (error) {
    console.error('Get versions error:', error);
    res.status(500).json({ error: 'Failed to get document versions' });
  }
});

// GET /api/docs/:id/versions/:versionId - Get specific version
router.get('/:id/versions/:versionId', async (req: AuthRequest, res) => {
  try {
    const { id, versionId } = req.params;

    const versionRecords = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.id, versionId))
      .limit(1);

    if (versionRecords.length === 0) {
      res.status(404).json({ error: 'Version not found' });
      return;
    }

    const version = versionRecords[0];

    // Get steps for this version
    const docSteps = await db.select()
      .from(steps)
      .where(eq(steps.versionId, versionId))
      .orderBy(steps.order);

    res.json({
      version,
      steps: docSteps
    });
  } catch (error) {
    console.error('Get version error:', error);
    res.status(500).json({ error: 'Failed to get version details' });
  }
});

// POST /api/docs/:id/versions/:versionId/restore - Restore a previous version
router.post('/:id/versions/:versionId/restore', async (req: AuthRequest, res) => {
  try {
    const { id, versionId } = req.params;
    const userId = req.user?.id;

    // Get the version to restore
    const versionRecords = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.id, versionId))
      .limit(1);

    if (versionRecords.length === 0) {
      res.status(404).json({ error: 'Version not found' });
      return;
    }

    const versionToRestore = versionRecords[0];

    // Get steps from the version to restore
    const oldSteps = await db.select()
      .from(steps)
      .where(eq(steps.versionId, versionId))
      .orderBy(steps.order);

    // Create new version with incremented number
    const versions = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, id))
      .orderBy(desc(documentVersions.versionNumber))
      .limit(1);

    const latestVersionNumber = versions[0]?.versionNumber || 0;
    const newVersionNumber = latestVersionNumber + 1;

    const newVersion = await db.insert(documentVersions).values({
      id: uuidv4(),
      documentId: id,
      versionNumber: newVersionNumber,
      versionLabel: `Restored from v${versionToRestore.versionNumber}`,
      changeDescription: `Restored from version ${versionToRestore.versionNumber}`,
      createdByUserId: userId || null
    }).returning();

    // Copy steps to new version
    for (const step of oldSteps) {
      await db.insert(steps).values({
        id: uuidv4(),
        documentId: id,
        versionId: newVersion[0].id,
        order: step.order,
        title: step.title,
        description: step.description,
        actionType: step.actionType,
        rawEventMetadata: step.rawEventMetadata,
        screenshotUrl: step.screenshotUrl,
        annotationMetadata: step.annotationMetadata,
        aiGenerated: step.aiGenerated,
        notes: step.notes
      });
    }

    // Update document's current version reference
    await db.update(documents).set({
      currentVersionId: newVersion[0].id,
      updatedAt: new Date()
    }).where(eq(documents.id, id));

    // Log audit event
    await db.insert(auditLogs).values({
      id: uuidv4(),
      orgId: (await db.select({ orgId: documents.orgId }).from(documents).where(eq(documents.id, id)).limit(1))[0].orgId,
      userId: userId || null,
      action: 'document.version.restore',
      entityType: 'document',
      entityId: id,
      metadata: { restoredFrom: versionId, newVersion: newVersion[0].id }
    });

    res.json({
      success: true,
      newVersion: newVersion[0]
    });
  } catch (error) {
    console.error('Restore version error:', error);
    res.status(500).json({ error: 'Failed to restore version' });
  }
});

// POST /api/docs/:id/version - Create new version manually
router.post('/:id/version', async (req: AuthRequest, res) => {
  try {
    const { id } = req.params;
    const { versionLabel, changeDescription } = req.body;
    const userId = req.user?.id;

    // Get current max version number
    const versions = await db.select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, id))
      .orderBy(desc(documentVersions.versionNumber))
      .limit(1);

    const latestVersionNumber = versions[0]?.versionNumber || 0;
    const newVersionNumber = latestVersionNumber + 1;

    const newVersion = await db.insert(documentVersions).values({
      id: uuidv4(),
      documentId: id,
      versionNumber: newVersionNumber,
      versionLabel: versionLabel || `Version ${newVersionNumber}`,
      changeDescription: changeDescription || 'Manual version creation',
      createdByUserId: userId || null
    }).returning();

    // Update document's current version reference
    await db.update(documents).set({
      currentVersionId: newVersion[0].id,
      updatedAt: new Date()
    }).where(eq(documents.id, id));

    res.json({
      success: true,
      version: newVersion[0]
    });
  } catch (error) {
    console.error('Create version error:', error);
    res.status(500).json({ error: 'Failed to create version' });
  }
});

export default router;
